name: Deploy Development

on:
  push:
    branches:
      - dev

jobs:
  deploy-development:
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render Development
        run: curl --fail --show-error --silent "${{ secrets.RENDER_DEPLOY_HOOK }}"